version: '3'
services:
  frontend:
    image: node:14
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
    working_dir: /src
    command: npm start
  backend:
    build: ./backend
    ports:
      - "5000:5000"
